# **Question 1** - Naive Bayes Classification 
Write a Python program to classify the given twitter dataset describing tweets on U.S airlines into positive, neutral and negative classes. Use suitable Na√Øve Bayes classification technique.

In [2]:
import nltk
import re
import pandas as pd
nltk.download('punkt')
nltk.download('stopwords')
from nltk.corpus import stopwords
stop_words = stopwords.words('english')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

In [3]:
dataset=pd.read_csv("/content/Tweets Dataset.csv")
dataset

,tweet_id,airline_sentiment,airline_sentiment_confidence,negativereason,negativereason_confidence,airline,airline_sentiment_gold,name,negativereason_gold,retweet_count,text,tweet_coord,tweet_created,tweet_location,user_timezone
0,5.700000e+17,neutral,1.0000,NaN,NaN,Virgin America,NaN,cairdin,NaN,0,@VirginAmerica What @dhepburn said.,NaN,24-02-15 11:35,NaN,Eastern Time (US & Canada)
1,5.700000e+17,positive,0.3486,NaN,0.0000,Virgin America,NaN,jnardino,NaN,0,@VirginAmerica plus you've added commercials t...,NaN,24-02-15 11:15,NaN,Pacific Time (US & Canada)
2,5.700000e+17,neutral,0.6837,NaN,NaN,Virgin America,NaN,yvonnalynn,NaN,0,@VirginAmerica I didn't today... Must mean I n...,NaN,24-02-15 11:15,Lets Play,Central Time (US & Canada)
3,5.700000e+17,negative,1.0000,Bad Flight,0.7033,Virgin America,NaN,jnardino,NaN,0,@VirginAmerica it's really aggressive to blast...,NaN,24-02-15 11:15,NaN,Pacific Time (US & Canada)
4,5.700000e+17,negative,1.0000,Can't Tell,1.0000,Virgin America,NaN,jnardino,NaN,0,@VirginAmerica and it's a really big bad thing...,NaN,24-02-15 11:14,NaN,Pacific Time (US & Canada)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
268,5.690000e+17,neutral,1.0000,NaN,NaN,Virgin America,NaN,fromtheleftseat,NaN,0,@VirginAmerica Adds Pillows Instead of Lie-Fla...,NaN,20-02-15 16:11,Phoenix AZ,Arizona
269,5.690000e+17,positive,0.6855,NaN,NaN,Virgin America,NaN,AlyssaJenS,NaN,0,@VirginAmerica I see what you did there ;),NaN,20-02-15 16:02,"Bay Area, CA",Pacific Time (US & Canada)
270,5.690000e+17,neutral,0.6803,NaN,NaN,Virgin America,NaN,Kevin_E_Park,NaN,0,@VirginAmerica way to take advantage of #Maywe...,NaN,20-02-15 15:50,NaN,Pacific Time (US & Canada)
271,5.690000e+17,neutral,1.0000,NaN,NaN,Virgin America,NaN,FlexinFinessinB,NaN,0,@VirginAmerica you know I'm flying virgin for ...,NaN,20-02-15 15:48,NaN,Central Time (US & Canada)
272,5.690000e+17,positive,1.0000,NaN,NaN,Virgin America,NaN,drsaadiaim,NaN,0,@VirginAmerica your inflight team makes the ex...,NaN,20-02-15 15:13,Boca Raton FL 33434,NaN

In [4]:
dataset=dataset.drop(columns=["tweet_id","airline_sentiment_confidence","negativereason","negativereason_confidence",
                    "airline","airline_sentiment_gold","name","negativereason_gold",
                    "retweet_count","tweet_coord","tweet_created","tweet_location",
                    "user_timezone"],axis=1)
dataset

    airline_sentiment                                               text
0             neutral                @VirginAmerica What @dhepburn said.
1            positive  @VirginAmerica plus you've added commercials t...
2             neutral  @VirginAmerica I didn't today... Must mean I n...
3            negative  @VirginAmerica it's really aggressive to blast...
4            negative  @VirginAmerica and it's a really big bad thing...
..                ...                                                ...
268           neutral  @VirginAmerica Adds Pillows Instead of Lie-Fla...
269          positive         @VirginAmerica I see what you did there ;)
270           neutral  @VirginAmerica way to take advantage of #Maywe...
271           neutral  @VirginAmerica you know I'm flying virgin for ...
272          positive  @VirginAmerica your inflight team makes the ex...

[273 rows x 2 columns]

In [7]:

for ele in dataset['text']:  
    ele1 = re.sub(r'[^\w\s]', '', ele)
    dataset['text'].replace({ele:ele1},inplace=True)


dataset['text'] = [s.lower() for s in dataset['text']]

def remove_stopwords(sen):
    sen_new = " ".join([i for i in sen if i not in stop_words])
    return sen_new

dataset['text'] = [remove_stopwords(r.split()) for r in dataset['text']]

In [9]:
# Training and Testing Splitting process
train=dataset[:180]
test=dataset[180:]
train

    airline_sentiment                                               text
0             neutral                        virginamerica dhepburn said
1            positive  virginamerica plus youve added commercials exp...
2             neutral  virginamerica didnt today must mean need take ...
3            negative  virginamerica really aggressive blast obnoxiou...
4            negative                 virginamerica really big bad thing
..                ...                                                ...
175           neutral  virginamerica id love know policy damaged luggage
176          positive                         virginamerica thank follow
177          negative  virginamerica many apologies r worse airlines ...
178          negative  virginamerica shame va making people spend mon...
179           neutral                          virginamerica ttinac11 dm

[180 rows x 2 columns]

In [10]:
# Writing down the all unique words
lst=[]
for i in train["text"]:
  k=i.split()
  for j in k:
      if j not in lst:
        lst.append(j)
lst

['virginamerica',
 'dhepburn',
 'said',
 'plus',
 'youve',
 'added',
 'commercials',
 'experience',
 'tacky',
 'didnt',
 'today',
 'must',
 'mean',
 'need',
 'take',
 'another',
 'trip',
 'really',
 'aggressive',
 'blast',
 'obnoxious',
 'entertainment',
 'guests',
 'faces',
 'amp',
 'little',
 'recourse',
 'big',
 'bad',
 'thing',
 'seriously',
 'would',
 'pay',
 '30',
 'flight',
 'seats',
 'playing',
 'flying',
 'va',
 'yes',
 'nearly',
 'every',
 'time',
 'fly',
 'vx',
 'ear',
 'worm',
 'wont',
 'go',
 'away',
 'missed',
 'prime',
 'opportunity',
 'men',
 'without',
 'hats',
 'parody',
 'httpstcomwpg7grezp',
 'well',
 'didntbut',
 'amazing',
 'arrived',
 'hour',
 'early',
 'youre',
 'good',
 'know',
 'suicide',
 'second',
 'leading',
 'cause',
 'death',
 'among',
 'teens',
 '1024',
 'lt3',
 'pretty',
 'graphics',
 'much',
 'better',
 'minimal',
 'iconography',
 'great',
 'deal',
 'already',
 'thinking',
 '2nd',
 'australia',
 'havent',
 'even',
 'gone',
 '1st',
 'yet',
 'p',
 'virginmedia',
 'im',
 'fabulous',
 'seductive',
 'skies',
 'u',
 'stress',
 'travel',
 'httptcoahlxhhkiyn',
 'thanks',
 'sfopdx',
 'schedule',
 'still',
 'mia',
 'excited',
 'first',
 'cross',
 'country',
 'lax',
 'mco',
 'ive',
 'heard',
 'nothing',
 'things',
 'virgin',
 'america',
 '29daystogo',
 'flew',
 'nyc',
 'sfo',
 'last',
 'week',
 'couldnt',
 'fully',
 'sit',
 'seat',
 'due',
 'two',
 'large',
 'gentleman',
 'either',
 'side',
 'help',
 'amazingly',
 'awesome',
 'bosfll',
 'please',
 'want',
 'fares',
 'may',
 'three',
 'times',
 'carriers',
 'available',
 'select',
 'love',
 'graphic',
 'httptcout5grrwaaa',
 'hipster',
 'innovation',
 'feel',
 'brand',
 'making',
 'bosgtlas',
 'non',
 'stop',
 'permanently',
 'anytime',
 'soon',
 'guys',
 'messed',
 'seating',
 'reserved',
 'friends',
 'gave',
 'free',
 'internet',
 'status',
 'match',
 'program',
 'applied',
 'weeks',
 'called',
 'emailed',
 'response',
 'happened',
 '2',
 'ur',
 'vegan',
 'food',
 'options',
 'least',
 'say',
 'site',
 'able',
 'eat',
 'anything',
 'next',
 '6',
 'hrs',
 'fail',
 'miss',
 'dont',
 'worry',
 'together',
 'cant',
 'get',
 'cold',
 'air',
 'vents',
 'vx358',
 'noair',
 'worstflightever',
 'roasted',
 'sfotobos',
 'ewr',
 'middle',
 'red',
 'eye',
 'noob',
 'maneuver',
 'sendambien',
 'andchexmix',
 'hi',
 'bked',
 'cool',
 'birthday',
 'add',
 'elevate',
 'entered',
 'name',
 'booking',
 'problems',
 'hours',
 'operation',
 'club',
 'posted',
 'online',
 'current',
 'left',
 'expensive',
 'headphones',
 '89',
 'iad',
 '2a',
 'one',
 'answering',
 'lampf',
 'number',
 'awaiting',
 'return',
 'phone',
 'call',
 'prefer',
 'use',
 'selfservice',
 'option',
 'news',
 'could',
 'start',
 'flights',
 'hawaii',
 'end',
 'year',
 'httptcor8p2zy3fe4',
 'via',
 'pacificbiznews',
 'nice',
 'rt',
 'vibe',
 'moodlight',
 'takeoff',
 'touchdown',
 'moodlitmonday',
 'sciencebehindtheexperience',
 'httptcoy7o0unxtqp',
 'moodlighting',
 'way',
 'best',
 'ever',
 'calming',
 'freddieawards',
 'done',
 'airline',
 'around',
 'hands',
 'book',
 'chat',
 'support',
 'working',
 'httptcovhp2gtdwpk',
 'view',
 'downtown',
 'los',
 'angeles',
 'hollywood',
 'sign',
 'beyond',
 'rain',
 'mountains',
 'httptcodw5nf0ibtr',
 'hey',
 'flyer',
 'hard',
 'getting',
 'account',
 'plz',
 'win',
 'bid',
 'upgrade',
 '227',
 'laxgtsea',
 'unused',
 'ticket',
 'moved',
 'new',
 'city',
 'expires',
 'travelhelp',
 'leaving',
 'dallas',
 'seattle',
 'feb',
 '24',
 'elevategold',
 'reason',
 'rock',
 'dream',
 'httptcooa2drfaoq2',
 'httptcolwwdac2khx',
 'wow',
 'blew',
 'mind',
 'ladygaga',
 'carrieunderwood',
 'night',
 'tribute',
 'soundofmusic',
 'oscars2015',
 'think',
 'agree',
 'entertaining',
 '769',
 'supposed',
 'minutes',
 'ago',
 'website',
 'shows',
 'julie',
 'andrews',
 'though',
 'impressive',
 'wish',
 'atlanta',
 'la',
 'february',
 '24th',
 '99',
 'lgagtdal',
 'trying',
 'since',
 'page',
 'never',
 'loads',
 'thx',
 'spotify',
 'stat',
 'guiltypleasures',
 'lady',
 'gaga',
 'carrie',
 'marketing',
 'song',
 'httpstcof2lfulcbq7',
 'let',
 'us',
 'wowd',
 'meh',
 '34',
 'adding',
 '3',
 '2014',
 'elevatethey',
 'shown',
 'uphelp',
 'sorry',
 'mary',
 'martin',
 'beat',
 'classics',
 '0736',
 'dal',
 'dca',
 '224',
 '210pm',
 'tried',
 'check',
 'heyyyy',
 'guyyyys',
 'someone',
 'hold',
 '4050',
 'earlier',
 'tonight',
 '1150pm',
 'congrats',
 'winning',
 'travelzoo',
 'award',
 'deals',
 'httptcokj1iljaebv',
 'everything',
 'fine',
 'lost',
 'bag',
 'change',
 'reservation',
 'credit',
 'card',
 'modify',
 'waive',
 'fee',
 'customer',
 'service',
 'team',
 'tracking',
 'booked',
 'baggage',
 'loft',
 'needs',
 'step',
 'game',
 '40',
 'dirty',
 'tables',
 'floors',
 'httptcohy0vrfhjht',
 'worried',
 'ride',
 'plane',
 'crew',
 'airlines',
 'like',
 'yall',
 'sat',
 'morning',
 'correct',
 'bill',
 'watch',
 'student',
 'films',
 '35000',
 'feet',
 'cmfat35000feet',
 'httptcokek5pdmgif',
 'different',
 'ratepolicy',
 'media',
 'bags',
 'going',
 'anyway',
 'speak',
 'human',
 'asap',
 'thank',
 'doom',
 'supp',
 'biz',
 'traveler',
 'southwestair',
 'jetblue',
 'neverflyvirginforbusiness',
 'member',
 'inflight',
 'teamim',
 '100',
 'interested',
 'flightattendant',
 'dreampath',
 'g',
 'whenever',
 'begrudgingly',
 'delayed',
 'late',
 'interesting',
 'cancelled',
 'four',
 'plannedneverflyvirginforbusiness',
 'disappointing',
 'shared',
 'business',
 'meet',
 'neverflyvirgin',
 'trouble',
 'wife',
 'httptcopx8hqoks3r',
 'bring',
 'using',
 'code',
 'random',
 'q',
 'whats',
 'distribution',
 'avatars',
 'bet',
 'kitty',
 'disproportionate',
 'share',
 'httptcoaptzpurop4',
 'life',
 'happens',
 'jperhi',
 'helpva',
 'home',
 'back',
 'rnp',
 'yeah',
 'points',
 'recent',
 'tv',
 'video',
 'disappointed',
 'flightled',
 'went',
 'jfk',
 'saturday',
 'landed',
 'friendly',
 'nomorevirgin',
 '345',
 'redirected',
 'btw',
 'isnt',
 'user',
 'redesign',
 'desktop',
 'mobile',
 'httptcoavyqdmpi1y',
 'scanned',
 'passengers',
 'leave',
 'told',
 'remove',
 'class',
 'bin',
 'uncomfortable',
 'find',
 'anyone',
 'useless',
 'boy',
 'prince',
 'ressie',
 'sf',
 'thursday',
 'httptcogsb2j3c4gm',
 'appointments',
 'sfo2lax',
 'music',
 'httptcomarcnocwzn',
 'hows',
 'direct',
 'fllgtsfo',
 'unexpected',
 'layover',
 'vegas',
 '4',
 'fuel',
 'peeps',
 'bought',
 'sneaky',
 'apt',
 'people',
 'exp',
 'raeann',
 'shes',
 'customerservice',
 'line',
 'hung',
 'sarcasm',
 'tripping',
 'plain',
 'text',
 'version',
 'reluctant',
 'enter',
 'info',
 'scheduled',
 '714',
 'changed',
 'weather',
 'looks',
 'getaway',
 '59',
 'oneway',
 'lots',
 'cities',
 'httptcotzzjhuibch',
 'cheapflights',
 'farecompare',
 'httptcorpdbpx3wnd',
 'httptcob2xi4yg5t8',
 'httptcoqdljhsloi5',
 'come',
 'phl',
 'horrible',
 'pleasecomeback',
 'httptcoglxfwp6nqh',
 'concerned',
 'tech',
 'flown',
 'oneasy',
 'reservationhelpful',
 'representatives',
 'comfortable',
 'rep',
 'kicked',
 'butt',
 'naelah',
 'represents',
 'beautifully',
 'beautiful',
 'frontend',
 'design',
 'right',
 'bc',
 'backend',
 'secure',
 'running',
 'gate',
 'e9',
 'las',
 'waited',
 'kept',
 'browser',
 '2015',
 'reputation',
 'built',
 'doesnt',
 'crossbrowser',
 'compatible',
 'totally',
 'folks',
 'problem',
 'min',
 'delay',
 'connecting',
 'seems',
 'long',
 'va370',
 'outstanding',
 'nycjfk',
 'san',
 'francisco',
 'absolute',
 'delighted',
 'provide',
 'complimentary',
 'upgrades',
 'thats',
 '9',
 '120',
 'wait',
 'calling',
 'intern',
 'completely',
 'month',
 'boslas',
 'nonstop',
 'depart',
 'vabeatsjblue',
 'jfkgtsfo',
 '882',
 'failing',
 'customers',
 'process',
 'link',
 'tsa',
 'precheck',
 'fidifamilies',
 'terrible',
 'hotel',
 'hotline',
 '276',
 'cabo',
 'lucas',
 'chrysichrysic',
 'assistance',
 'yesterday',
 'give',
 'shame',
 'likingyoulessandless',
 'register',
 'dog',
 'gt',
 'dulles',
 'queue',
 'longer',
 'pls',
 'advise',
 'oscars',
 'redcarpet',
 'reallytallchris',
 'dropped',
 'track',
 'httpstcozv2pt6trk9',
 'always',
 'xoxo',
 'buy',
 'creates',
 'anxiety',
 'frustrated',
 'youd',
 'paying',
 'extra',
 'bucks',
 'luggage',
 'might',
 'afford',
 'hiring',
 'hand',
 'lame',
 'world',
 'irmafromdallas',
 'takes',
 'cake',
 'flt',
 'sooner',
 'midnight',
 'monday',
 'imagine',
 'web',
 'indicates',
 'dude',
 'andor',
 'staff',
 'super',
 'helpful',
 'ran',
 'waltdisneyworld',
 'princesshalf',
 'spoiled',
 'comfort',
 'paid',
 'premium',
 'across',
 'offer',
 'sad',
 'face',
 'question',
 'possible',
 'infant',
 'giving',
 'welcome',
 'jessicajaymes',
 'dc',
 'sunset',
 'globe',
 'backtowinter',
 'work',
 'refreshed',
 'httptcovx9vbctdlf',
 'understand',
 'dm',
 'answer',
 'damaged',
 'policy',
 'destroyed',
 'special',
 'alone',
 'w2',
 'kids',
 '1',
 'priority',
 'boarding',
 'checking',
 'tickets',
 'purchased',
 'happy',
 'coming',
 '713',
 'field',
 'definitely',
 '23',
 '0769',
 'lga',
 'dfw',
 'drivers',
 'license',
 'expired',
 'friday',
 'keeps',
 'error',
 'contact',
 'minute',
 'reschedule',
 'button',
 'greyed',
 'rang',
 '35',
 'vendor',
 'fix',
 'got',
 '450',
 'todaychecked',
 'email',
 'tomorrow',
 'unacceptable',
 'flighted',
 'stuck',
 'today12',
 'pairings',
 'include',
 'wine',
 'white',
 'offered',
 'redwineisbetter',
 'wonked',
 'look',
 'browsers',
 'css',
 'httptco8qsqmm7kf2',
 'agent',
 'designated',
 'silver',
 'dulles_airport',
 'closed',
 'assist',
 'pasengers',
 'plans',
 'austin',
 'route',
 'topnews',
 'arab',
 'emirates',
 'httptcoaqzwecokk2',
 'normal',
 'receive',
 'reply',
 'central',
 'baggageissues',
 'smh',
 'logan',
 'airport',
 'waiting',
 'checkin',
 '9am',
 'desk',
 'open',
 'jump',
 'dallasaustin',
 'market',
 'dallas_news',
 'httptcoewwgi97gdx',
 'beats',
 'eps',
 'views',
 'luv',
 'investors',
 'daily',
 'httptcoflwmgdahxu',
 'lister',
 'show',
 '1230',
 '130',
 'begin',
 'april',
 '889',
 'ketr',
 'httptcossuvwwkyhh',
 'sfolax',
 'fuck',
 'united',
 'fl1289',
 'sfoewr',
 'clincher',
 'id',
 'follow',
 'many',
 'apologies',
 'r',
 'worse',
 'respond',
 'cudtomers',
 'spend',
 'money',
 'stranded',
 'landing',
 'reimburse',
 'ttinac11']

In [11]:
f_st=[]
for i in train['text']:
  st=[]
  k=i.split()
  for wrd in lst:
      if wrd not in k:
        st.append(0)
      else:
        st.append(1)
  f_st.append(st)

train.insert(1,'f_set',f_st)
train

,airline_sentiment,f_set,text
0,neutral,"[1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",virginamerica dhepburn said
1,positive,"[1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, ...",virginamerica plus youve added commercials exp...
2,neutral,"[1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, ...",virginamerica didnt today must mean need take ...
3,negative,"[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",virginamerica really aggressive blast obnoxiou...
4,negative,"[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",virginamerica really big bad thing
...,...,...,...
175,neutral,"[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",virginamerica id love know policy damaged luggage
176,positive,"[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",virginamerica thank follow
177,negative,"[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",virginamerica many apologies r worse airlines ...
178,negative,"[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",virginamerica shame va making people spend mon...
179,neutral,"[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",virginamerica ttinac11 dm

In [12]:
p=0
neg=0
neu=0
for i in train['airline_sentiment']:
  if i =='positive':
    p+=1
  elif i =="neutral":
    neu+=1
  else:
    neg+=1

prob_p=p/(p+neg+neu)
prob_neg=neg/(p+neg+neu)
prob_neu=neu/(p+neg+neu)
print("Probability of being a positive class:",prob_p)
print("Probability of being a negative class:",prob_neg)
print("Probability of being a neutral class:",prob_neu)

Probability of being a positive class: 0.2611111111111111
Probability of being a negative class: 0.4
Probability of being a neutral class: 0.3388888888888889

In [13]:
#total number of words in positive and negative class respectively
pc=0
neg_c=0
neu_c=0
for i in range(180):
  if train['airline_sentiment'][i]=='positive':
    for j in train['f_set'][i]:
      pc+=j
  elif train['airline_sentiment'][i]=='neutral':
    for j in train['f_set'][i]:
      neu_c+=j
  else:
    for j in train['f_set'][i]:
      neg_c+=j

print("Positive class word count:",pc)
print("Negative class word count:",neg_c)
print("Neutral class word count:",neu_c)

Positive class word count: 420
Negative class word count: 813
Neutral class word count: 507

In [16]:
p_lst=[]
pf=[]
nf=[]
neu=[]
for i in range(180):
  k=train['text'][i].split()
  for j in k:
    c=1
    s=1
    n=1
    if j not in p_lst:
      p_lst.append(j)
      for _ in range(180):
        if train['airline_sentiment'][_]=='positive':
          m=train['text'][_].split()
          if j in m:
            c+=1
        if train['airline_sentiment'][_]=='neutral':
          m=train['text'][_].split()
          if j in m:
            n+=1
        else:
          m=train['text'][_].split()
          if j in m:
            s+=1
      pf.append(c)
      nf.append(s)
      neu.append(n)
print("Positive word counts with smoothing-->",pf)
print("Neutral word counts with smoothing->>",neu)
print("Negative word counts with smoothing-->",nf)

Positive word counts with smoothing--> [48, 1, 1, 2, 2, 2, 2, 5, 2, 1, 1, 1, 1, 3, 3, 2, 2, 2, 1, 1, 1, 1, 1, 1, 4, 1, 1, 1, 1, 1, 1, 2, 1, 1, 6, 1, 1, 5, 1, 2, 2, 3, 4, 5, 2, 2, 2, 2, 2, 3, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 5, 2, 2, 2, 3, 4, 3, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 6, 2, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 5, 2, 2, 2, 2, 2, 2, 2, 4, 1, 1, 2, 1, 2, 2, 2, 2, 2, 2, 3, 2, 2, 3, 2, 3, 2, 2, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 4, 2, 2, 2, 1, 3, 2, 1, 1, 1, 1, 5, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 5, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 1, 1, 1, 1, 2, 1, 1, 2, 4, 8, 3, 2, 2, 2, 4, 2, 2, 2, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 3, 1, 1, 1, 2, 2, 2, 4, 4, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 1, 2, 2, 2, 2, 4, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 5, 4, 4, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 4, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 5, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 3, 3, 3, 2, 3, 3, 1, 2, 1, 2, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 3, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
Neutral word counts with smoothing->> [62, 2, 2, 1, 1, 1, 1, 1, 1, 2, 3, 2, 2, 5, 3, 2, 3, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 2, 15, 2, 1, 3, 3, 1, 1, 1, 5, 3, 1, 1, 1, 1, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, 1, 1, 1, 1, 6, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 3, 1, 1, 3, 1, 1, 5, 1, 2, 4, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 5, 3, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 3, 1, 1, 1, 2, 1, 3, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 4, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 3, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 3, 1, 3, 1, 4, 3, 1, 1, 2, 2, 2, 2, 2, 2, 5, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 4, 2, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 3, 4, 2, 2, 2, 1, 1, 1, 2, 2, 2, 1, 1, 1, 8, 8, 3, 2, 2, 3, 3, 2, 2, 2, 2, 2, 2, 3, 2, 3, 3, 1, 1, 2, 2, 2, 3, 3, 1, 1, 3, 1, 2, 1, 1, 1, 1, 1, 1, 2, 2, 3, 2, 2, 2, 4, 3, 2, 2, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 1, 1, 2, 3, 2, 2, 2, 2, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 1, 1, 1, 1, 1, 3, 3, 2, 2, 2, 2, 2, 3, 3, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 3, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 2, 2, 2, 2, 2, 2, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 1, 3, 3, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 2, 2, 4, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2]
Negative word counts with smoothing--> [120, 1, 2, 2, 2, 3, 2, 7, 2, 2, 3, 2, 2, 6, 3, 5, 3, 5, 2, 2, 2, 2, 2, 2, 7, 3, 2, 2, 3, 3, 2, 4, 2, 3, 28, 4, 2, 8, 3, 2, 2, 4, 8, 7, 2, 2, 2, 3, 2, 4, 3, 1, 1, 1, 1, 1, 1, 1, 2, 2, 6, 2, 5, 2, 4, 4, 4, 1, 1, 1, 2, 1, 1, 1, 1, 2, 2, 2, 3, 2, 2, 2, 7, 3, 3, 2, 2, 2, 4, 4, 2, 3, 3, 2, 2, 14, 2, 2, 2, 3, 2, 3, 2, 4, 2, 2, 4, 2, 4, 5, 2, 3, 5, 2, 5, 3, 2, 3, 3, 3, 2, 3, 3, 4, 4, 6, 2, 2, 2, 5, 3, 3, 2, 2, 2, 2, 6, 2, 6, 2, 4, 5, 2, 5, 5, 2, 2, 2, 2, 6, 2, 2, 2, 2, 2, 3, 3, 1, 1, 2, 1, 1, 1, 2, 2, 2, 2, 2, 3, 2, 2, 4, 2, 2, 4, 4, 5, 2, 3, 2, 6, 2, 2, 2, 2, 2, 2, 9, 2, 2, 3, 5, 2, 2, 2, 2, 5, 1, 2, 9, 5, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 4, 2, 6, 2, 3, 4, 2, 2, 4, 4, 2, 1, 1, 1, 3, 1, 2, 2, 2, 2, 2, 2, 3, 3, 2, 4, 2, 2, 7, 4, 2, 4, 2, 3, 2, 3, 2, 9, 2, 2, 2, 2, 2, 2, 1, 3, 1, 1, 1, 1, 2, 1, 1, 2, 4, 9, 3, 2, 2, 2, 7, 2, 2, 6, 2, 2, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2, 2, 2, 3, 3, 1, 1, 1, 2, 1, 1, 1, 4, 2, 3, 1, 1, 1, 1, 3, 1, 1, 1, 2, 2, 3, 1, 1, 1, 2, 2, 2, 4, 4, 1, 1, 1, 2, 2, 1, 2, 2, 1, 3, 3, 6, 1, 2, 2, 2, 2, 1, 1, 2, 1, 1, 2, 2, 4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 2, 5, 1, 1, 2, 3, 2, 2, 2, 2, 2, 2, 1, 1, 2, 2, 1, 1, 1, 1, 1, 3, 10, 2, 2, 3, 2, 2, 2, 4, 2, 3, 2, 2, 2, 4, 2, 2, 2, 4, 7, 4, 2, 1, 2, 1, 1, 2, 8, 9, 4, 1, 2, 2, 2, 3, 2, 2, 3, 2, 2, 2, 2, 2, 2, 4, 4, 4, 5, 2, 2, 3, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 6, 1, 2, 2, 4, 2, 2, 2, 2, 2, 2, 3, 2, 2, 2, 2, 2, 2, 5, 5, 3, 7, 2, 2, 2, 2, 6, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 5, 1, 1, 1, 1, 2, 2, 4, 4, 2, 3, 2, 2, 2, 2, 1, 1, 2, 3, 2, 2, 2, 2, 2, 2, 3, 2, 4, 2, 3, 2, 2, 2, 2, 2, 1, 1, 1, 2, 1, 1, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2, 2, 2, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, 1, 3, 3, 3, 3, 4, 2, 3, 3, 1, 2, 1, 2, 2, 2, 2, 2, 2, 3, 2, 2, 2, 2, 2, 3, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, 2, 2, 4, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 1, 1, 1, 2, 2, 2, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 2, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 2, 2, 2, 3, 2, 2, 2, 2, 2, 2, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1]

In [17]:
#creating a probability dataframe for easier understanding
pos_prob=pd.DataFrame(lst,columns=["Word"])
neg_prob=pd.DataFrame(lst,columns=["Word"])
neu_prob=pd.DataFrame(lst,columns=["Word"])

In [18]:
st=[]
st1=[]
st2=[]
for i in pf:
  v=i/(pc+len(lst))
  st.append(v)

for i in nf:
  v=i/(neg_c+len(lst))
  st1.append(v)

for i in neu:
  v=i/(neu_c+len(lst))
  st2.append(v)

pos_prob.insert(1,'prob',st)
neg_prob.insert(1,'prob',st1)
neu_prob.insert(1,'prob',st2)

In [19]:

pos_prob

              Word      prob
0    virginamerica  0.036838
1         dhepburn  0.000767
2             said  0.000767
3             plus  0.001535
4            youve  0.001535
..             ...       ...
878          money  0.000767
879       stranded  0.000767
880        landing  0.000767
881      reimburse  0.000767
882       ttinac11  0.000767

[883 rows x 2 columns]

In [20]:

neg_prob

              Word      prob
0    virginamerica  0.070755
1         dhepburn  0.000590
2             said  0.001179
3             plus  0.001179
4            youve  0.001179
..             ...       ...
878          money  0.001179
879       stranded  0.001179
880        landing  0.001179
881      reimburse  0.001179
882       ttinac11  0.000590

[883 rows x 2 columns]

In [21]:

neu_prob

              Word      prob
0    virginamerica  0.044604
1         dhepburn  0.001439
2             said  0.001439
3             plus  0.000719
4            youve  0.000719
..             ...       ...
878          money  0.000719
879       stranded  0.000719
880        landing  0.000719
881      reimburse  0.000719
882       ttinac11  0.001439

[883 rows x 2 columns]

In [22]:
def det_class(tst):
  # Positive class:
  k=tst.split()
  td=[]
  for i in k:
    td.append(pos_prob.index[pos_prob['Word']==i].tolist())
  td1=[]
  for i in td:
    for j in i:
      td1.append(j)

  pos_val=1
  for i in td1:
    pos_val*=pos_prob['prob'][i]

  pos_val*=prob_p

  

  # Negative class:
  td=[]
  for i in k:
    td.append(neg_prob.index[neg_prob['Word']==i].tolist())
  td1=[]
  for i in td:
    for j in i:
      td1.append(j)

  neg_val=1
  for i in td1:
    neg_val*=neg_prob['prob'][i]

  neg_val*=prob_neg



  #for neutral class:
  td=[]
  for i in k:
    td.append(neu_prob.index[neu_prob['Word']==i].tolist())
  td1=[]
  for i in td:
    for j in i:
      td1.append(j)

  neu_val=1
  for i in td1:
    neu_val*=neu_prob['prob'][i]

  neu_val*=prob_neu
  

  if pos_val>neg_val:
    if pos_val>neu_val:
      return "positive"
    else:
      return "neutral"
  elif neg_val>pos_val:
    if neg_val<neu_val:
      return "neutral"
    else:
      return "negative"

In [23]:
test_data_1= "Serving bad Food absolutely perfect Restaurant"
test_data_1=remove_stopwords(test_data_1.lower().split())
c=det_class(test_data_1)
if c=='negative':
  print("yes")

yes

In [24]:
tp=0
fp=0
fn=0
tn=0
for i,j in zip(test['text'],test['airline_sentiment']):
  i=remove_stopwords(i.lower().split())
  if (det_class(i) == "positive" and j=="positive") or (det_class(i)=="neutral" and j=="neutral"):
    tp+=1
  elif det_class(i)=="positive" and j!="positive":
    fp+=1
  elif det_class(i)=="negative" and j!="negative":
    fn+=1  
  elif det_class(i)=="negative" and j=="negative":
    tn+=1

In [25]:
acc=(tp+tn)/(tp+tn+fp+fn)
print("Accuracy is--->",acc)

Accuracy is---> 0.46153846153846156

In [26]:
prs=(tp)/(tp+fp)
print("Precision is--->",prs)

Precision is---> 1.0

In [27]:
rec=(tp)/(tp+fn)
print("Recall--->",rec)

Recall---> 0.057692307692307696

In [28]:
fscore=2*(prs*rec)/(prs+rec)
print("F1 score is--->",fscore)

F1 score is---> 0.1090909090909091